name: Rebuild all

on:
  workflow_dispatch:
    inputs:
      packages:
        description: Space-separated packages (empty for all)
        type: string
        default: ''
        required: false
  schedule:
    - cron: "0 8 * * 3"

jobs:
  check:
    name: Rebuild
    runs-on: ubuntu-latest
    steps:
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install Composer dependencies
        run: composer install
      -
        name: Update packages
        run: ./bin/pecl-info update --ansi --no-interaction --update-packages --update-package-details --update-versions -- ${{ inputs.packages }}
      -
        name: Check changes
        id: check-changes
        run: |
          PUSH=no
          printf 'Checking changes in downloaded XML files...'
          if test -n "$(git status --porcelain xml)"; then
            printf 'changes detected!\n'
            git add --all xml
            PUSH=yes
          else
            printf 'no changes detected.\n'
          fi
          printf 'Checking changes in generated JSON files (public)...'
          if test -n "$(git status --porcelain public)"; then
            printf 'changes detected!\n'
            git add --all public
            PUSH=yes
          else
            printf 'no changes detected.\n'
          fi
          printf 'Checking changes in generated JSON files (docs/data)...'
          if test -n "$(git status --porcelain docs/data)"; then
            printf 'changes detected!\n'
            git add --all docs/data
            PUSH=yes
          else
            printf 'no changes detected.\n'
          fi
          printf 'push=%s\n' "$PUSH" >> $GITHUB_OUTPUT
      -
        name: Configure git
        if: steps.check-changes.outputs.push == 'yes'
        run: |
          git config --local user.name 'GitHub'
          git config --local user.email 'noreply@github.com'
      -
        name: Commit changed files
        if: steps.check-changes.outputs.push == 'yes'
        run: git commit -m 'Rebuilding all packages'
      -
        name: Push back to the remote repository
        if: steps.check-changes.outputs.push == 'yes'
        run: git push
